source "https://rubygems.org"

gem "activerecord", "~> 6.1"
gem "sinatra", "~> 2.1"
gem "sinatra-activerecord", "~> 2.0"

gem "rake"
gem "sqlite3", "~> 1.4"
gem "require_all"
gem "rack-contrib", "~> 2.3"
gem "rack-cors", "~> 1.1"



group :development do
  gem 'rerun'
  gem "pry"
end